#!/usr/bin/env node

/**
 * Module dependencies.
 */

var app = require('./app'), argv = require('yargs').argv,
    fs = require('fs'), https = require('https'),
    debug = require('debug')('shellcreeper:server'),
    http = require('http');

/**
 * Get port from environment and store in Express.
 */

var port = normalizePort(argv.port || '3000');
app.set('port', port);

console.log("shellcreeper is running on port "+port);

var options = {}, server;

if (argv.key && argv.cert){
    options.cert = fs.readFileSync(argv.cert);
    options.key = fs.readFileSync(argv.key);
    try {
        options.ca = fs.readFileSync(argv.chain);

    } catch(err){

    }
    var server = https.createServer(options, app).listen(port, function(){

    });
} else {
  var server = http.createServer(app, options);
}

/**
 * Create HTTP server.
 */



/**
 * Listen on provided port, on all network interfaces.
 */

server.listen(port);
server.on('error', onError);
server.on('listening', onListening);

/**
 * Normalize a port into a number, string, or false.
 */

function normalizePort(val) {
  var port = parseInt(val, 10);

  if (isNaN(port)) {
    // named pipe
    return val;
  }

  if (port >= 0) {
    // port number
    return port;
  }

  return false;
}

/**
 * Event listener for HTTP server "error" event.
 */

function onError(error) {
  if (error.syscall !== 'listen') {
    throw error;
  }

  var bind = typeof port === 'string'
    ? 'Pipe ' + port
    : 'Port ' + port;

  // handle specific listen errors with friendly messages
  switch (error.code) {
    case 'EACCES':
      console.error(bind + ' requires elevated privileges');
      process.exit(1);
      break;
    case 'EADDRINUSE':
      console.error(bind + ' is already in use');
      process.exit(1);
      break;
    default:
      throw error;
  }
}

/**
 * Event listener for HTTP server "listening" event.
 */

function onListening() {
  var addr = server.address();
  var bind = typeof addr === 'string'
    ? 'pipe ' + addr
    : 'port ' + addr.port;
  debug('Listening on ' + bind);
}
